### PR TITLE
Added theme outline to project

### PR DESCRIPTION
**Pull request by raulpineda**

### CODE REVIEW

**Comment by kevinsimper** [comment]
I wonder how the best way to learn javascript is? When i learned javascript, my first experience was jQuery and I had no need for learning loops/if/boolean etc.

**Comment by raulpineda** [comment]
@kevinsimper we had that discussion during both planning meetings, and since most of 5he girls have zero programming experience, we'd like to stay away from libraries and introduce basic concepts before DOM manipulation

**Comment by kevinsimper** [comment]
@raulpineda Yes, I understand what you mean :smile: but a question all the girls would have: "why would you want to learn javascript?", and the answer would most likely be: "to make interactive webpages", or am i wrong?

**Comment by raulpineda** [comment]
@kevinsimper probably yes, but that's why we have two js workshops, this is an introduction to the language and the second one will be focused on website interactivity - basically DOM manipulation.

**Comment by kevinsimper** [comment]
ahh nice :+1:

**Pull request merged**
